pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/docker-brandr-api
    volumes:
      - /tmp/cache:/cache

  build-branch:
    image: plugins/docker
    repo: scienta/brandr-api
    dockerfile: docker/Dockerfile
    context: ./
    auto_tag: false
    tags: "branch-${DRONE_BRANCH}"
    storage_path: /drone/docker-brandr-api
    secrets: [ docker_username, docker_password ]
    when:
      event: [push]

  build-tag:
    image: plugins/docker
    repo: scienta/brandr-api
    dockerfile: docker/Dockerfile
    context: ./
    auto_tag: false
    tags: "${DRONE_TAG}"
    storage_path: /drone/docker-brandr-api
    secrets: [ docker_username, docker_password ]
    when:
      event: [tag]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/docker-ids
    volumes:
      - /tmp/cache:/cache

