version: '3.2'
services:
  brandr-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "${BIND_INTERFACE}:9080:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=dev
      - API_ENDPOINT=${API_ENDPOINT}
      - DEBUG=*,-navigator:info,-sequelize*,-koa*,-nodemon*,-snapdragon*,-puppeteer*
    command: ["yarn", "run", "dev"]
